// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZoDTj6Is5mCYfC9EPrJynmFGt6Dcx24',
    appId: '1:550081917613:web:9afd89490eddb605eccc24',
    messagingSenderId: '550081917613',
    projectId: 'siyaq-dc1a6',
    authDomain: 'siyaq-dc1a6.firebaseapp.com',
    storageBucket: 'siyaq-dc1a6.firebasestorage.app',
    measurementId: 'G-Y935G8G43X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bCLTtajlROjupSXl70fnK-L3akne2GU',
    appId: '1:550081917613:android:bb03f00614c3ff66eccc24',
    messagingSenderId: '550081917613',
    projectId: 'siyaq-dc1a6',
    storageBucket: 'siyaq-dc1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRCCaG44diCxMam9bod0PZczwyijxvwTc',
    appId: '1:550081917613:ios:c54e55cc474c3821eccc24',
    messagingSenderId: '550081917613',
    projectId: 'siyaq-dc1a6',
    storageBucket: 'siyaq-dc1a6.firebasestorage.app',
    iosBundleId: 'com.siyaq.siyaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRCCaG44diCxMam9bod0PZczwyijxvwTc',
    appId: '1:550081917613:ios:c54e55cc474c3821eccc24',
    messagingSenderId: '550081917613',
    projectId: 'siyaq-dc1a6',
    storageBucket: 'siyaq-dc1a6.firebasestorage.app',
    iosBundleId: 'com.siyaq.siyaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOZoDTj6Is5mCYfC9EPrJynmFGt6Dcx24',
    appId: '1:550081917613:web:27786bba71551410eccc24',
    messagingSenderId: '550081917613',
    projectId: 'siyaq-dc1a6',
    authDomain: 'siyaq-dc1a6.firebaseapp.com',
    storageBucket: 'siyaq-dc1a6.firebasestorage.app',
    measurementId: 'G-73QXG45VGS',
  );
}
